### ISSUE TITLE
Taint specific states

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#263]
**What would you like to add**
I really need the option of tainting specific states. Today I had to recreate the AKS cluster due to a name change in the unit (tfmodule). However, the dependent helm modules of the unit were not recreated and were shown as “No change” in the `cdev plan`. Thus, we also need to check modules for compliance with the current infrastructure and the possibility of manual redeployment through tainting of specific states.

**Comment by romanprog** [comment]
Hello.
Such an option already exists. You can run the apply command with the --ignore-state option (`cdev apply --ignore-state`). With this option, cdev will apply the all units regardless of whether the state has changed. This option is safe, it will only take more time, since the validation of the state of the terraform in each unit will be performed. Also, after execution, the project state will be synchronized with current project configuration.
ps
The name of the units is an immutable value. It is not recommended to change the names of units.

**Comment by kinseii** [comment]
Great! Just what I need!
